name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: docker build -t eaziguy/week7-app:v1 ./app

    - name: Push image to Docker Hub
      run: docker push eaziguy/week7-app:v1

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: 13.61.187.115
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker pull eaziguy/week7-app:v1
          sudo docker rm -f $(sudo docker ps -aq) || true
          sudo docker run -d -p 8080:80 eaziguy/week7-app:v1
